backend:
  name: github
  repo: dreitagebart/musikkapelle-markelsheim

site_url: https://www.musikkapelle-markelsheim.de
publish_mode: editorial_workflow
media_folder: content/assets
public_folder: ../assets

collections:
  - name: events
    label: Termine
    folder: content/events
    create: true
    fields:
      - { name: path, label: Slug }
      - { name: title, label: Titel }
      - { name: date, label: Datum, widget: datetime }
      - { name: location, label: Ort }

  - name: events
    label: Termine
    folder: content/events
    create: true
    fields:
      - { name: path, label: Slug }
      - { name: title, label: Titel }
      - { name: date, label: Datum, widget: datetime }
      - { name: body, label: Text, widget: markdown }

  - name: front
    label: Startseite
    folder: content/front
    create: true
    fields:
      - { name: path, label: Slug }
      - { name: date, label: Datum, widget: date }
      - { name: title, label: Titel }
      - { name: body, label: Text, widget: markdown }
